### ISSUE TITLE
How long does it take to train the model?

### ISSUE THREAD

**Issue by zq0x7a0x71** [MinkaiXu/CGCF-ConfGen#3]
Thanks for sharing the code!

I tried to train the model using a single RTX3090 card. The expected training time is around 20 days when max_iters is 1000*1000. Is it a normal case?

**Comment by luost26** [comment]
Hi Zhanqiu,

For ``Drugs`` dataset, we trained the model for around 30K iterations. For ``QM9`` dataset, 45K iterations.
The training time for both of the models is about 1.5 days on a single 2080ti GPU.

We will change the default value of ``max_iters`` to a reasonable value. 

Thanks

**Comment by zq0x7a0x71** [comment]
Thank you for your prompt reply!
